# Package import
Let's import necessary packages:

In [ ]:
!pip install install scikit-learn==0.23.2
!pip install hmni
import pandas as pd, hmni
state_names=["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"]
def findavgbias(polls):
    avg=sum(polls)/len(polls)
    return avg
matcher = hmni.Matcher(model='latin')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 46.4 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.5 requires scikit-learn>=1.0.0, but you have scikit-learn 0.23.2 which is incompatible.
imbalanced-learn 0.8.1 requires scikit-learn>=0.24, but you have scikit-learn 0.23.2 which is incompatible.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.2/22.2 MB 14.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.9/235.9 KB 19.1 MB/s eta 0:00:00


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator MaxAbsScaler from version 0.23.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator MinMaxScaler from version 0.23.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.23.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.23.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use

# Collecting polls
We collect the polls

In [ ]:
senidict=dict()
senpolls=pd.read_csv('senate_polls_historical.csv')
senres=pd.read_csv('2016-2020-senate.csv')
senpolls=senpolls[senpolls['state'].isin(state_names)]
for i in set(senpolls['race_id']):
    senidict[i]=senpolls[(senpolls['race_id']==i) & (senpolls['fte_grade']!='F')]
    for j in set(senidict[i]['question_id']):
        poll=senidict[i][senidict[i]['question_id']==j].sort_values('pct',ascending=0)
        leader=tuple(poll['answer'])[0]
        ttparties=tuple(poll['party'])[:2]
        pcts=tuple(poll['pct'])
        mov=pcts[0]-pcts[1]
        if not('DEM' in ttparties and 'REP' in ttparties):
            senidict[i]=senidict[i].drop(poll.index)
    if len(senidict[i].index)>0:
        year,state=list(set(senidict[i]['cycle']))[0],list(set(senidict[i]['state']))[0].upper()
        actual=senres[(senres['year']==year) & (senres['state']==state)].sort_values('candidatevotes',ascending=0)
        adem,arep=list(actual[actual['party_simplified'].str.startswith('DEM')]['candidate'])[0],list(actual[actual['party_simplified'].str.startswith('REP')]['candidate'])[0]
        dems=set(senidict[i][senidict[i]['party']=='DEM']['candidate_name'])
        reps=set(senidict[i][senidict[i]['party']=='REP']['candidate_name'])
        fgfggfgff=0
        if len(dems)>1:
            g=[]
            fgfggfgff+=1
            print(year,state)
            print('D: ',dems)
            for j in dems:
                m=matcher.similarity(j,adem)
                print(j,adem,m)
                g.append((m,j))
            if max(g)[0]==0:
                input((g,adem))
        if len(reps)>1:
            g=[]
            fgfggfgff+=1
            print(year,state)
            print('R: ',reps)
            for j in reps:
                m=matcher.similarity(j,arep)
                print(j,arep,m)
                g.append((m,j))
            if max(g)[0]==0:
                input((g,arep))
        if fgfggfgff>0:
            print('-------------------')

In [ ]:
houseidict=dict()
housepolls=pd.read_csv('house_polls_historical.csv')
houseres=pd.read_csv('1976-2020-house.csv')
housepolls=housepolls[housepolls['state'].isin(state_names)]
for i in set(housepolls['race_id']):
    houseidict[i]=housepolls[housepolls['race_id']==i]
    for j in set(houseidict[i]['question_id']):
        poll=houseidict[i][houseidict[i]['question_id']==j].sort_values('pct',ascending=0)
        leader=tuple(poll['answer'])[0]
        ttparties=tuple(poll['party'])[:2]
        pcts=tuple(poll['pct'])
        mov=pcts[0]-pcts[1]
        if not('DEM' in ttparties and 'REP' in ttparties):
            houseidict[i]=houseidict[i].drop(poll.index)
    if len(houseidict[i].index)>0:
        year,state,district=list(set(houseidict[i]['cycle']))[0],list(set(houseidict[i]['state']))[0].upper(),list(set(houseidict[i]['seat_number']))[0]
        if district>1:
            actual=houseres[(houseres['year']==year) & (houseres['state']==state) & (houseres['district']==district)].sort_values('candidatevotes',ascending=0)
        else:
            actual=houseres[(houseres['year']==year) & (houseres['state']==state) & ((houseres['district']==1) | (houseres['district']==0))].sort_values('candidatevotes',ascending=0)
        actual['party']=actual['party'].fillna('OTHER')
        dems=set(houseidict[i][houseidict[i]['party']=='DEM']['candidate_name'])
        reps=set(houseidict[i][houseidict[i]['party']=='REP']['candidate_name'])

        # adem,arep=list(actual[actual['party'].str.startswith('DEM')]['candidate'])[0],list(actual[actual['party'].str.startswith('REP')]['candidate'])[0]


        try:
            adem,arep=list(actual[actual['party'].str.startswith('DEM')]['candidate'])[0],list(actual[actual['party'].str.startswith('REP')]['candidate'])[0]
        except:
            print(year,state,district,dems,reps)
            print(actual)
            input()
        fgfggfgff=0
        if len(dems)>1:
            g=[]
            fgfggfgff+=1
            print(year,state,district)
            print('D: ',dems)
            for j in dems:
                m=matcher.similarity(j,adem)
                print(j,adem,m)
                g.append((m,j))
            if max(g)[0]==0:
                input((g,adem))
        if len(reps)>1:
            g=[]
            fgfggfgff+=1
            print(year,state,district)
            print('R: ',reps)
            for j in reps:
                m=matcher.similarity(j,arep)
                print(j,arep,m)
                g.append((m,j))
            if max(g)[0]==0:
                input((g,arep))
        if fgfggfgff>0:
            print('-------------------')

In [ ]:
presidict=dict()
prespolls=pd.read_csv('president_polls_historical.csv')
presres=pd.read_csv('1976-2020-president.csv')
prespolls=prespolls[prespolls['state'].isin(state_names)]
for i in set(prespolls['race_id']):
    presidict[i]=prespolls[(prespolls['race_id']==i) & (prespolls['fte_grade']!='F')]
    for j in set(presidict[i]['question_id']):
        poll=presidict[i][presidict[i]['question_id']==j].sort_values('pct',ascending=0)
        leader=tuple(poll['answer'])[0]
        ttparties=tuple(poll['party'])[:2]
        pcts=tuple(poll['pct'])
        mov=pcts[0]-pcts[1]
        if not('DEM' in ttparties and 'REP' in ttparties):
            presidict[i]=presidict[i].drop(poll.index)
    if len(presidict[i].index)>0:
        year,state=list(set(presidict[i]['cycle']))[0],list(set(presidict[i]['state']))[0].upper()
        actual=presres[(presres['year']==year) & (presres['state']==state)].sort_values('candidatevotes',ascending=0)
        adem,arep=list(actual[actual['party_simplified'].str.startswith('DEM')]['candidate'])[0],list(actual[actual['party_simplified'].str.startswith('REP')]['candidate'])[0]
        dems=set(presidict[i][presidict[i]['party']=='DEM']['candidate_name'])
        reps=set(presidict[i][presidict[i]['party']=='REP']['candidate_name'])
        fgfggfgff=0
        if len(dems)>1:
            g=[]
            fgfggfgff+=1
            print(year,state)
            print('D: ',dems)
            for j in dems:
                m=matcher.similarity(j,adem)
                print(j,adem,m)
                g.append((m,j))
            if max(g)[0]==0:
                input((g,adem))
        if len(reps)>1:
            g=[]
            fgfggfgff+=1
            print(year,state)
            print('R: ',reps)
            for j in reps:
                m=matcher.similarity(j,arep)
                print(j,arep,m)
                g.append((m,j))
            if max(g)[0]==0:
                input((g,arep))
        if fgfggfgff>0:
            print('-------------------')

In [ ]:
import pandas as pd

In [ ]:
allpolls,allresults,alltop={},{},{}
pollsterbiases={}

pollstername={}

mainparties=['DEM','REP']
for office in ['house','senate','president','governor']:
    polls=pd.read_csv(office+'_polls_historical.csv')
    if office=='governor':
        electionr=pd.read_csv('election_results_gubernatorial.csv')
    elif office=='president':
        electionr=pd.read_csv('election_results_presidential.csv')
    else:
        electionr=pd.read_csv('election_results_'+office+'.csv')
    print(office)
    pollraceids=set(polls['race_id'])
    for race in set(electionr['race_id']):
        er=electionr[electionr['race_id']==race]
        allcandids=set(er['candidate_id'])
        if len(allcandids)!=len(er):
            for candidate in allcandids:
                candidatesection=er[er['candidate_id']==candidate]
                if len(candidatesection)>1:
                    demrep=candidatesection[candidatesection['ballot_party'].isin(mainparties)]
                    if len(demrep)==1:
                        winningindex=list(demrep.index)[0]
                        er=er.drop(index=set(candidatesection.index))
                        candidatesection=candidatesection.drop(index=winningindex)
                        demrep.at[winningindex,'votes']+=candidatesection['votes'].sum()
                        demrep.at[winningindex,'percent']+=candidatesection['percent'].sum()
                        er=er.append(demrep)
                    elif len(demrep)==0:
                        er=er.drop(index=set(candidatesection.index))
                        winningindex=candidatesection['votes'].idxmax()
                        replacement=candidatesection.loc[[winningindex]]
                        candidatesection=candidatesection.drop(index=winningindex)
                        replacement.at[winningindex,'votes']+=candidatesection['votes'].sum()
                        replacement.at[winningindex,'percent']+=candidatesection['percent'].sum()
                        er=er.append(replacement)
        er=er.sort_values('votes',ascending=0)
        if race in pollraceids:
            winning=er.head(2)
            alltop[race]={(winning.loc[index,'ballot_party'],winning.loc[index,'candidate_id'],winning.loc[index,'percent']) for index in winning.index}
            if sorted(winning['ballot_party'])==mainparties:
                allracepolls=polls[(polls['race_id']==race) & (polls['fte_grade']!='F')]
                allpolls[race]=[]
                for question in set(allracepolls['question_id']):
                    piq=allracepolls[allracepolls['question_id']==question]
                    if len(piq[piq['candidate_id'].isin(winning['candidate_id'])])==2:
                        allpolls[race].append(piq.sort_values('pct',ascending=0))


                        pollsterid=tuple(set(piq['pollster_id']))[0]
                        pollstern=tuple(set(piq['pollster']))[0]
                        if pollsterid in pollstername:
                            pollstername[pollsterid].add(pollstern)
                        else:
                            pollstername[pollsterid]={pollstern}
                        pollsterbiases[pollsterid]=[]
                allresults[race]=er
            # else:
            #     info=(race,list(er['cycle'])[0],list(er['state'])[0],list(er['office_name'])[0],list(er['office_seat_name'])[0],list(er['stage'])[0])
            #     print(info)
            #     print(er[['candidate_name','ballot_party']])
allpolls[438],allresults[438],alltop[438]

house
senate


/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (14,15,21,23) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


president
governor


([      poll_id  pollster_id pollster sponsor_ids sponsors display_name  \
  2438    56183          907     GBAO         NaN      NaN         GBAO   
  2437    56183          907     GBAO         NaN      NaN         GBAO   
  
        pollster_rating_id pollster_rating_name fte_grade methodology  ...  \
  2438                 109                 GBAO       B/C         NaN  ...   
  2437                 109                 GBAO       B/C         NaN  ...   
  
         seat_name election_date    stage  nationwide_batch  \
  2438  District 1       11/6/18  general             False   
  2437  District 1       11/6/18  general             False   
  
       ranked_choice_reallocated party   answer  candidate_id candidate_name  \
  2438                     False   REP   Zeldin         11888  Lee M. Zeldin   
  2437                     False   DEM  Gershon         11887  Perry Gershon   
  
         pct  
  2438  49.5  
  2437  46.2  
  
  [2 rows x 42 columns],
        poll_id  pollster_i

In [ ]:
# determine biases
for race in allresults:
    toptwo=sorted(alltop[race])
    margin=toptwo[0][2]-toptwo[1][2]
    candids={toptwo[0][1],toptwo[1][1]}
    for poll in allpolls[race]:
        prestt=[]
        pid=tuple(set(poll['pollster_id']))[0]
        for candidate in toptwo:
            pcands=poll[poll['candidate_id']==candidate[1]]
            prestt.append(tuple(pcands['pct'])[0])
        pollmargin=prestt[0]-prestt[1]
        pollsterbiases[pid].append(margin-pollmargin)
print(len(pollsterbiases))






    # made df which has entry for poll/question id, datetime object for the end date, basic race information, margin of victory

350


In [ ]:
polldf=pd.DataFrame()

b=[(len(pollsterbiases[pollster]),sum(pollsterbiases[pollster])/len(pollsterbiases[pollster]),list(pollstername[pollster])[0]) for pollster in pollsterbiases]
c=[(sum(pollsterbiases[pollster])/len(pollsterbiases[pollster]),len(pollsterbiases[pollster]),list(pollstername[pollster])[0]) for pollster in pollsterbiases]

for pollster in pollsterbiases:
    print(pollster,pollstername[pollster],sum(pollsterbiases[pollster]),len(pollsterbiases[pollster]),sum(pollsterbiases[pollster])/len(pollsterbiases[pollster]))

print(sorted(b,reverse=1))
print(sorted(c,reverse=1))

# scale down simple average maybe?

# polldf

940 {'Lake Research'} -56.824909546843706 17 -3.34264173804963
1334 {'Alaska Survey Research'} -27.887453140401647 20 -1.3943726570200823
383 {'PPP'} -1181.8417986282705 284 -4.1614147839023605
211 {'Hendrix College'} -56.7582236838221 11 -5.1598385167111
1240 {'Øptimus'} -60.276329167032905 23 -2.6207099637840394
1456 {'Go Right Strategies'} 25.48530675826511 2 12.742653379132555
24 {'American Viewpoint'} 30.634187080377217 13 2.356475929259786
1424 {'Siena College/NYT Upshot'} -243.89467461051606 292 -0.8352557349675208
1293 {'OH Predictive Insights / MBQF'} -65.24905880132113 37 -1.7634880757113818
921 {'Clarity'} -40.2871189551316 5 -8.05742379102632
379 {'POS'} 30.061797166549432 26 1.1562229679442089
1363 {'UC Berkeley'} -7.832763272420358 13 -0.602520251724643
172 {'Garin Hart Yang'} -298.8218589902741 42 -7.1148061664350974
460 {'SurveyUSA'} -201.56055904080586 110 -1.8323687185527806
1365 {'Change Research'} -912.7299615970918 238 -3.8349998386432427
603 {'Strategies 360'} -57

# Building the Model

Now we built the model!

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, Model
from matplotlib import pyplot as plt
from collections import Counter
import pandas as pd
import numpy as np

In [ ]:
pollinfo=pd.read_csv('allpolls_numerical_a.csv')
pollinfo

poll_id                 pollster_name  race_id      office  cycle  \
0       86020                 Lake Research      167  U.S. House   2018   
1       91243        Alaska Survey Research      167  U.S. House   2018   
2       90224                           PPP      167  U.S. House   2018   
3       90452        Alaska Survey Research      167  U.S. House   2018   
4       90069        Alaska Survey Research      167  U.S. House   2018   
...       ...                           ...      ...         ...    ...   
9982   134436     Triton Polling & Research     7828    Governor   2020   
9983   132057     Triton Polling & Research     7828    Governor   2020   
9984   132154          Strategies Unlimited     7828    Governor   2020   
9985   129818  Mark Blankenship Enterprises     7828    Governor   2020   
9986   132252         Research America Inc.     7828    Governor   2020   

              state  district    stage  days_before_election  sample_size  \
0            Alaska         1  general                   147        540.0   
1            Alaska         1  general                     8        500.0   
2            Alaska         1  general                    25        645.0   
3            Alaska         1  general                    23        500.0   
4            Alaska         1  general                    31        500.0   
...             ...       ...      ...                   ...          ...   
9982  West Virginia         0  general                    14        544.0   
9983  West Virginia         0  general                    34        525.0   
9984  West Virginia         0  general                    34        600.0   
9985  West Virginia         0  general                    50        504.0   
9986  West Virginia         0  general                    28        450.0   

      ...  pollster_id_1691  pollster_id_1692  pollster_id_1704  \
0     ...                 0                 0                 0   
1     ...                 0                 0                 0   
2     ...                 0                 0                 0   
3     ...                 0                 0                 0   
4     ...                 0                 0                 0   
...   ...               ...               ...               ...   
9982  ...                 0                 0                 0   
9983  ...                 0                 0                 0   
9984  ...                 0                 0                 0   
9985  ...                 0                 0                 0   
9986  ...                 0                 0                 0   

      partisan_poll_-1  partisan_poll_0  partisan_poll_1  population_sample_a  \
0                    0                0                1                    0   
1                    0                1                0                    0   
2                    0                0                1                    0   
3                    0                1                0                    0   
4                    0                1                0                    0   
...                ...              ...              ...                  ...   
9982                 0                1                0                    0   
9983                 0                1                0                    0   
9984                 0                0                1                    0   
9985                 1                0                0                    0   
9986                 0                1                0                    0   

      population_sample_lv  population_sample_rv  population_sample_v  
0                        1                     0                    0  
1                        1                     0                    0  
2                        0                     0                    1  
3                        1                     0                    0  
4                        1                

In [ ]:
data=pollinfo.drop(columns=['poll_id','pollster_name','office','cycle','state','district','stage','predicted_margin'])
att,pred=data.drop(columns=['actual_margin']),data['actual_margin']
# i_pollres = tf.keras.Input(shape=(1,))

# i_dbe = tf.keras.Input(shape=(1,))
# i_size = tf.keras.Input(shape=(1,))
# i_pop = tf.keras.Input(shape=(4,))
# i_psterid = tf.keras.Input(shape=(350,))
# i_ppoll = tf.keras.Input(shape=(3,))
races=[]
x=[]
y=[]
for i in set(att['race_id']):
    races.append(i)
    race=att[att['race_id']==i].drop(columns=['race_id'])
    necessarydata=[race[['poll_after_bias']],race[['days_before_election']],race[['sample_size']],race[[j for j in race if j.startswith('population_sample')]],race[[j for j in race if j.startswith('pollster_id')]],race[[j for j in race if j.startswith('partisan_poll')]]]
    # x.append(np.array([j.values.tolist() for j in necessarydata]))
    x.append([j.to_numpy() for j in necessarydata])
    # print(x[0])
    # print(x[0].shape)
    # input()
    (m,)=tuple(set(pred[race.index]))
    mm=np.array([[m],[0],[0],[0]])
    mm=np.array([[m]])
    # mm=mm.reshape(4,-1)
    y.append(mm)
# print(race.index,y[race.index])
# x.to_numpy()
for i in x[0]:
    print(i,i.shape)
print(y[0])
# len(x),len(y)
# np.dstack(x)


[[ -3.10259425]
 [ -8.10259425]
 [-12.40047698]
 [ -1.67156411]] (4, 1)
[[ 49]
 [106]
 [ 91]
 [ 12]] (4, 1)
[[400.]
 [400.]
 [500.]
 [432.]] (4, 1)
[[0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]] (4, 4)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] (4, 350)
[[0 0 1]
 [0 0 1]
 [1 0 0]
 [0 0 1]] (4, 3)
[[-12.19663108]]


In [ ]:
class aaaaaAAAAAAA()

In [ ]:
class weightedaverage(layers.Layer):
    def __init__(self):
        super(weightedaverage, self).__init__()
    def call(self,inputs):
        res=inputs[0]
        wei=inputs[1]
        weightedsum=tf.math.reduce_sum(tf.multiply(res,wei))
        weightsum=tf.math.reduce_sum(wei)
        return tf.divide(weightedsum,weightsum)
class sumall(layers.Layer):
    def __init__(self):
        super(sumall, self).__init__()
    def call(self,inputs):
        return tf.math.reduce_sum(inputs)
# add constraints

i_pollres = tf.keras.Input(shape=(1,))

i_dbe = tf.keras.Input(shape=(1,))
i_size = tf.keras.Input(shape=(1,))
i_pop = tf.keras.Input(shape=(4,))
i_psterid = tf.keras.Input(shape=(350,))
i_ppoll = tf.keras.Input(shape=(3,))

d_dbe=layers.Dense(1)(i_dbe)
d_size=layers.Dense(1)(i_size)
d_pop=layers.Dense(1,use_bias=False)(i_pop)
d_psterid=layers.Dense(1,use_bias=False)(i_psterid)
d_ppoll=layers.Dense(1,use_bias=False)(i_ppoll)

fweight=layers.multiply([d_dbe,d_size,d_pop,d_psterid,d_ppoll])

wavlayer=weightedaverage()([i_pollres,fweight])

sum1=sumall()(wavlayer)
sum2=sumall()(sum1)

# output=layers.Dot(axes=1)([i_pollres,fweight])

model = tf.keras.Model(inputs=[i_pollres,i_dbe,i_size,i_pop,i_psterid,i_ppoll], outputs=sum2)
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_14 (InputLayer)          [(None, 1)]          0           []                               
                                                                                                  
 input_15 (InputLayer)          [(None, 1)]          0           []                               
                                                                                                  
 input_16 (InputLayer)          [(None, 4)]          0           []                               
                                                                                                  
 input_17 (InputLayer)          [(None, 350)]        0           []                               
                                                                                            

In [ ]:
model.compile(metrics="mean_absolute_error",loss="mean_squared_error",run_eagerly=True)
model.fit(x[0],y[0])

ValueError: ignored

In [ ]:
for n,i in enumerate(x):
    result=model.predict(i,batch_size=1000)
    if type(result)!=float:
        print(result,y[n],races[n])

52/52 [==============================] - 1s 9ms/step
[  4.9537582    6.990023     5.3901877    4.1523566    2.7990346
          nan   1.360639    -2.5132291    8.07944      3.3363132
   2.4677026    2.5601506    3.6962302    0.63661635   0.209347
   0.7113455    2.7246096    2.9737992    4.390976     6.5046487
  14.097312    18.493937     1.6741956   19.865713     3.978052
   3.2202222    7.672054     2.6742191  -28.920214     1.1605325
   4.659999     4.396464     1.2864655    4.4404283    4.090908
   6.6513224    7.454263     4.9686003    6.137932     5.467796
   4.356879     0.63891065   2.0295067    1.1404235    3.9042044
   0.70460594   3.1761286   -2.1339452   -8.778844     5.712529
   4.630735     2.191943  ] [[4.45297452]] 6210
2/2 [==============================] - 0s 13ms/step
[-17.467665   -5.4884963] [[-10.061191]] 6211
2/2 [==============================] - 0s 14ms/step
[-27.91656  -27.699078] [[-25.46165295]] 6212
2/2 [==============================] - 0s 10ms/step
[-40.0

In [ ]:
model.predict(x[races.index(6210)])

(32, 1) (32, 1)
tf.Tensor(-283802.94, shape=(), dtype=float32) tf.Tensor(-45545.703, shape=(), dtype=float32) tf.Tensor(6.2311683, shape=(), dtype=float32)
 1/52 [..............................] - ETA: 3s(32, 1) (32, 1)
tf.Tensor(-427025.5, shape=(), dtype=float32) tf.Tensor(-130812.61, shape=(), dtype=float32) tf.Tensor(3.2644062, shape=(), dtype=float32)
(32, 1) (32, 1)
tf.Tensor(-784204.5, shape=(), dtype=float32) tf.Tensor(-145487.4, shape=(), dtype=float32) tf.Tensor(5.390188, shape=(), dtype=float32)
(32, 1) (32, 1)
tf.Tensor(-692267.9, shape=(), dtype=float32) tf.Tensor(-160654.25, shape=(), dtype=float32) tf.Tensor(4.3090544, shape=(), dtype=float32)
(32, 1) (32, 1)
tf.Tensor(-122709.89, shape=(), dtype=float32) tf.Tensor(-45521.76, shape=(), dtype=float32) tf.Tensor(2.6956315, shape=(), dtype=float32)
(32, 1) (32, 1)
tf.Tensor(nan, shape=(), dtype=float32) tf.Tensor(nan, shape=(), dtype=float32) tf.Tensor(nan, shape=(), dtype=float32)
(32, 1) (32, 1)
tf.Tensor(-34255.754, shap

array([  6.2311683 ,   3.2644062 ,   5.390188  ,   4.3090544 ,
         2.6956315 ,          nan,   1.7453469 ,   0.5985688 ,
         5.1573777 ,   3.384018  ,   2.4677024 ,   2.5601506 ,
         3.69623   ,   1.0135715 ,   0.20934701,   0.7113455 ,
         2.7246096 , -36.36552   ,  -4.244145  ,   5.6916857 ,
         6.7070723 ,   6.768119  ,   3.6127062 , -30.429453  ,
         2.417903  ,   3.974629  ,   4.470373  ,  -1.3937368 ,
         3.771995  ,   0.7904804 ,   4.659999  ,   4.4038854 ,
         5.223948  ,  18.197979  , -14.600635  ,   3.5224211 ,
        11.825565  ,   6.586936  ,  17.718319  ,   0.18896008,
        32.84313   ,   1.7122811 ,  -9.022492  ,   1.849195  ,
         5.490685  ,  -7.409021  ,   6.4213963 ,   0.7907516 ,
         0.5524504 ,  32.94976   ,   2.840236  ,   0.82132095],
      dtype=float32)

In [ ]:
x[races.index(6210)][0].shape
tf.Tensor().to_numpy()

(1640, 1)